server {
    listen 80;
    server_name test-mango;

    root /var/www/html;

    location / {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_pass php:9000;
    }
}
